[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
envy = "0.4.2"
serde = "1.0.190"
serde_json = "1.0.108"
solana-account-decoder = "1.17.4"
solana-client = "1.17.4"
solana-sdk = "1.17.4"
spl-associated-token-account = "2.2.0"
spl-token = "4.0.0"
url = { version = "2.4.1", features = ["serde"] }
