[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.33"
envy = "0.4.2"
futures-util = "0.3.30"
serde = "1.0.195"
serde_json = "1.0.111"
solana-account-decoder = "1.18.8"
solana-client = "1.18.8"
solana-sdk = "1.18.8"
spl-associated-token-account = "2.3.0"
spl-token = "4.0.0"
tokio = "1.36.0"
url = { version = "2.5.0", features = ["serde"] }
