[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
envy = "0.4.2"
mpl-token-metadata = "1.2.5"
serde = "1.0.137"
serde_json = "1.0.81"
solana-client = "1.10.24"
solana-sdk = "1.10.24"
spl-associated-token-account = "1.0.3"
spl-token = "3.2.0"
url = { version = "2.2.2", features = ["serde"] }
