[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
chrono = "0.4.19"
envy = "0.4.2"
mpl-token-metadata = "1.3.1"
serde = "1.0.137"
serde_json = "1.0.81"
solana-account-decoder = "1.10.26"
solana-client = "1.10.26"
solana-sdk = "1.10.26"
spl-associated-token-account = "1.0.5"
spl-token = "3.3.0"
url = { version = "2.2.2", features = ["serde"] }
